create table attraction_info
(
    latitude        float(53),
    longitude       float(53),
    content_id      bigint generated by default as identity,
    content_type_id bigint,
    gugun_code      bigint,
    read_count      bigint,
    sido_code       bigint,
    addr1           varchar(255),
    addr2           varchar(255),
    first_image     varchar(255),
    first_image2    varchar(255),
    mlevel          varchar(255),
    tel             varchar(255),
    title           varchar(255),
    zipcode         varchar(255),
    primary key (content_id)
);

create table jwt_token
(
    created_at timestamp(6),
    user_id    bigint not null,
    token      clob,
    primary key (user_id)
);

create table plan
(
    plan_id     integer generated by default as identity,
    user_id     integer,
    created_at  timestamp(6),
    date        timestamp(6),
    modified_at timestamp(6),
    content     varchar(255),
    primary key (plan_id)
);

create table travel_plan
(
    attraction_info_id integer,
    id                 integer generated by default as identity,
    order_index        integer,
    plan_id            integer,
    primary key (id)
);

create table users
(
    id       bigint generated by default as identity,
    email    varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);