spring:
  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      schema-locations: "classpath*:./db/schema.sql"
      data-locations: "classpath*:./db/data.sql"
      mode: never


jwt:
  token:
    access-header: ${JWT_ACCESS_HEADER:ENC(wCDnLXsQpxmETxULplUl/FQK040NhP50)}
    refresh-header: ${JWT_REFRESH_HEADER:ENC(7w2hCckNkFDU0fhPsHYPVPRgQIP5F8D2xCSZ1WSqOl0=)}
    issuer: ${JWT_ISSUER:ENC(2a4b4nIfQ71azDnMx//jIOG2nZT+xbGIYzNUwI807aM=)}
    client-secret: ${JWT_SECRET:ENC(OoBtxYPhAJ0MlixnVsTUD1rMxvsU+csy)}
    access-expiry-seconds: 1
    refresh-expiry-seconds: 5000
encryptor:
  key: ${ENCRYPTOR_KEY:ENV(YjMC1MxZrt/OAUySn0Nc1dUgvaKMW87tT5+vqncccaQ=)}
